---
data:
  target_language: "sparql"
  train: "dataset/lcquad/tmcd_split/english_train_split_coef_0.1.json"
  dev: "dataset/lcquad/tmcd_split/english_dev_split_coef_0.1.json"
  test: "dataset/lcquad/tmcd_split/english_test_split_coef_0.1.json"
  dataset_vocab: "dataset/lcquad/query_vocab.json"
  schema:
    sql:
      add_schema_to_input_flag: True
      db_attributes_dict: "dataset/wikisql/table_id2new_attrs_for_parsing.json"
      db2db_path: "dataset/wikisql/table_name2db_path_dict.json"
    sparql:
      add_schema_to_input_flag: False
  compound_cache_path: "dataset/lcquad/tmcd_split/"

model:
  used_model: "t5"
  vanilla:
    tokenizer: "cointegrated/rubert-tiny"
    model: "cointegrated/rubert-tiny"
    enable_attention: True
    epochs_num: 120
    bert_finetune_rate: 0.00006
    learning_rate: 0.0005
    bert_warmup_init_finetuning_learning_rate: 0.00003
    warm_up_init_learning_rate: 0.0005
    warmup_steps: 4000
    batch_size: 32
    n_last_layers2train: 1
    use_pretrained_embeddings: False
    pretrained_embeddings_path: "experiments/pretrained_lm_sparql_embs.pt"
    embeddings_size: 300
  t5:
    tokenizer: "t5-base"
    model: "t5-base"
    epochs_num: 100
    learning_rate: 0.0015
    batch_size: 32
    optimizer: 'adam'


test_one_batch: False
run_name: "tmcd_sparql_hmt_control_v5"

# for testing
model_type: 'mt'
hard_mt: True
save_model_path: "experiments"
inference_model_name: "tmcd_sparql_hmt_control_v5/epoch_94_tm_0.85_t5.pt"